import { SUPABASE_CONFIG } from './config.js';

const params=new URLSearchParams(location.search),slug=(params.get('barangay')||'').trim().toLowerCase();
const form=document.querySelector('#signup-form'),status=document.querySelector('#signup-status'),button=document.querySelector('#signup-button'),title=document.querySelector('#signup-title'),subtitle=document.querySelector('#signup-subtitle'),back=document.querySelector('#back-login');
let targetBarangay=null;
function show(message,error=false){status.hidden=false;status.textContent=message;status.dataset.state=error?'error':'ok'}
async function loadBarangay(){if(!slug){form.hidden=true;show('This signup link must include a barangay.',true);return}try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/barangays?slug=eq.${encodeURIComponent(slug)}&status=eq.active&select=id,name,slug,municipality,province&limit=1`,{headers:{apikey:SUPABASE_CONFIG.publishableKey}});if(!r.ok)throw new Error('Unable to load barangay.');const rows=await r.json();targetBarangay=rows[0];if(!targetBarangay){form.hidden=true;show('This barangay is inactive or does not exist.',true);return}title.textContent=`${targetBarangay.name} Admin Sign up`;subtitle.textContent=`Request an admin account for ${targetBarangay.name}. Super Admin approval is required before login.`;if(back)back.href=`login.html?barangay=${encodeURIComponent(targetBarangay.slug)}`;}catch(e){form.hidden=true;show(e.message||'Unable to load barangay.',true)}}
form.addEventListener('submit',async e=>{e.preventDefault();if(!targetBarangay)return;const full_name=document.querySelector('#full-name').value.trim(),email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,confirm=document.querySelector('#confirm-password').value;if(!full_name||!email||!password){show('Complete all required fields.',true);return}if(password!==confirm){show('Passwords do not match.',true);return}if(password.length<8){show('Password must be at least 8 characters.',true);return}button.disabled=true;show('Submitting your account for approval…');try{const r=await fetch(`${SUPABASE_CONFIG.url}/auth/v1/signup`,{method:'POST',headers:{apikey:SUPABASE_CONFIG.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{full_name,barangay_id:targetBarangay.id,requested_role:'barangay_admin'}})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Unable to create account.');show('Account submitted. Wait for Super Admin approval before signing in.');form.reset();button.disabled=true;}catch(err){show(err instanceof Error?err.message:'Signup failed.',true);button.disabled=false}});
loadBarangay();
