import { SUPABASE_CONFIG } from './config.js';

const params=new URLSearchParams(location.search),requestedSlug=(params.get('barangay')||'').trim().toLowerCase();
const form=document.querySelector('#signup-form'),status=document.querySelector('#signup-status'),button=document.querySelector('#signup-button'),title=document.querySelector('#signup-title'),subtitle=document.querySelector('#signup-subtitle'),back=document.querySelector('#back-login'),barangaySelect=document.querySelector('#barangay');
let targetBarangay=null,barangays=[];
function show(message,error=false){status.hidden=false;status.textContent=message;status.dataset.state=error?'error':'ok'}
async function loadBarangays(){try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/barangays?status=eq.active&select=id,name,slug,municipality,province&order=name.asc`,{headers:{apikey:SUPABASE_CONFIG.publishableKey}});if(!r.ok)throw new Error('Unable to load barangays.');barangays=await r.json();barangaySelect.innerHTML='<option value="">Select a barangay…</option>'+barangays.map(b=>`<option value="${b.id}">${String(b.name).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}</option>`).join('');if(requestedSlug){const match=barangays.find(b=>b.slug===requestedSlug);if(match){barangaySelect.value=match.id;setTarget(match)}}if(!barangays.length)show('No active barangays are available for admin requests.',true)}catch(e){form.hidden=true;show(e.message||'Unable to load barangays.',true)}}
function setTarget(b){targetBarangay=b||null;if(!targetBarangay)return;title.textContent=`${targetBarangay.name} Admin Sign up`;subtitle.textContent=`Request an admin account for ${targetBarangay.name}. Super Admin approval is required before login.`;if(back)back.href=`login.html?barangay=${encodeURIComponent(targetBarangay.slug)}`}
barangaySelect.addEventListener('change',()=>setTarget(barangays.find(b=>b.id===barangaySelect.value)||null));
form.addEventListener('submit',async e=>{e.preventDefault();targetBarangay=barangays.find(b=>b.id===barangaySelect.value)||null;if(!targetBarangay){show('Select the barangay you want to administer.',true);return}const full_name=document.querySelector('#full-name').value.trim(),email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,confirm=document.querySelector('#confirm-password').value;if(!full_name||!email||!password){show('Complete all required fields.',true);return}if(password!==confirm){show('Passwords do not match.',true);return}if(password.length<8){show('Password must be at least 8 characters.',true);return}button.disabled=true;show('Submitting your account for approval…');try{const r=await fetch(`${SUPABASE_CONFIG.url}/auth/v1/signup`,{method:'POST',headers:{apikey:SUPABASE_CONFIG.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{full_name,barangay_id:targetBarangay.id,requested_role:'barangay_admin'}})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Unable to create account.');show(`Request submitted for ${targetBarangay.name}. Wait for Super Admin approval before signing in.`);form.reset();barangaySelect.value='';targetBarangay=null;button.disabled=true;}catch(err){show(err instanceof Error?err.message:'Signup failed.',true);button.disabled=false}});
loadBarangays();
