import { SUPABASE_CONFIG } from './config.js';
const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');
const welcome=document.querySelector('#welcome'),list=document.querySelector('#barangays'),dashboardList=document.querySelector('#dashboard-list'),form=document.querySelector('#barangay-form'),status=document.querySelector('#status'),search=document.querySelector('#search'),cancel=document.querySelector('#cancel'),save=document.querySelector('#save');
const adminForm=document.querySelector('#admin-form'),adminStatus=document.querySelector('#admin-status'),adminSave=document.querySelector('#admin-save'),adminBarangay=document.querySelector('#admin-barangay'),adminQueue=document.querySelector('#admin-queue');
const fields=['name','slug','municipality','province'];let barangays=[],admins=[];
function isAdmin(){return session?.access_token&&session?.profile&&String(session.profile.role).toLowerCase()==='super_admin'&&session.profile.approval_status==='approved'}
function show(m,error=false){status.textContent=m;status.dataset.state=error?'error':'ok';status.hidden=false}
function showAdmin(m,error=false){adminStatus.textContent=m;adminStatus.dataset.state=error?'error':'ok';adminStatus.hidden=false}
function headers(extra={}){return{apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...extra}}
if(!isAdmin()){sessionStorage.removeItem('brgywebsaas_session');window.location.replace('login.html')}else{welcome.textContent=`Signed in as ${session.profile.full_name||session.user.email}`;loadBarangays();loadAdmins()}
function renderStats(){document.querySelector('#total-count').textContent=barangays.length;document.querySelector('#active-count').textContent=barangays.filter(b=>b.status==='active').length;document.querySelector('#inactive-count').textContent=barangays.filter(b=>b.status!=='active').length}
function renderDashboard(){dashboardList.innerHTML=barangays.slice(0,6).map(b=>`<div class="list-group-item px-0 py-3" style="background:transparent;border-color:var(--border)"><div class="d-flex justify-content-between gap-3 flex-wrap"><div><strong>${escapeHtml(b.name)}</strong><div class="muted small">${escapeHtml(b.municipality||'')} ${escapeHtml(b.province||'')}</div></div><span class="badge text-bg-${b.status==='active'?'success':'secondary'}">${escapeHtml(b.status)}</span></div></div>`).join('')||'<p class="muted mb-0">No barangays yet.</p>'}
async function loadBarangays(){try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/barangays?select=id,name,slug,municipality,province,status,created_at&order=name.asc`,{headers:headers()});if(!r.ok)throw new Error('Unable to load barangays.');barangays=await r.json();render();renderStats();renderDashboard();populateAdminBarangays()}catch(e){show(e.message||'Unable to load barangays.',true)}}
function populateAdminBarangays(){const current=adminBarangay.value;adminBarangay.innerHTML='<option value="">Select a barangay…</option>'+barangays.filter(b=>b.status==='active').map(b=>`<option value="${escapeHtml(b.id)}">${escapeHtml(b.name)}</option>`).join('');if(barangays.some(b=>b.id===current&&b.status==='active'))adminBarangay.value=current}
function render(){const q=search.value.trim().toLowerCase();const rows=barangays.filter(b=>[b.name,b.slug,b.municipality,b.province].some(v=>String(v||'').toLowerCase().includes(q)));list.innerHTML=rows.length?rows.map(b=>`<article><div><strong>${escapeHtml(b.name)}</strong><div class="muted">${escapeHtml(b.municipality||'')} ${escapeHtml(b.province||'')} · ${escapeHtml(b.status)}</div></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-edit="${b.id}" type="button">Edit</button><button class="btn btn-sm btn-outline-secondary" data-toggle="${b.id}" type="button">${b.status==='active'?'Deactivate':'Activate'}</button></div></article>`).join(''):'<div class="muted py-3">No barangays found.</div>'}
function renderAdmins(){if(!admins.length){adminQueue.innerHTML='<div class="muted py-3">No Barangay Admin accounts yet.</div>';return}adminQueue.innerHTML=admins.map(a=>{const b=barangays.find(x=>x.id===a.barangay_id);const state=a.approval_status||'pending';return `<article><div><strong>${escapeHtml(a.full_name||'Unnamed admin')}</strong><div class="muted">${escapeHtml(a.email||'')} · ${escapeHtml(b?.name||'Unassigned')}</div><div class="small mt-1">Status: <strong>${escapeHtml(state)}</strong></div></div><div class="d-flex gap-2 flex-wrap">${state!=='approved'?`<button class="btn btn-sm btn-primary" data-approve="${a.id}" type="button">Approve</button>`:''}${state!=='rejected'?`<button class="btn btn-sm btn-outline-danger" data-reject="${a.id}" type="button">Reject</button>`:''}</div></article>`}).join('')}
async function loadAdmins(){try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/profiles?role=eq.barangay_admin&select=id,full_name,role,barangay_id,approval_status&order=created_at.desc`,{headers:headers()});if(!r.ok)throw new Error('Unable to load admin accounts.');admins=await r.json();renderAdmins()}catch(e){adminQueue.innerHTML=`<div class="muted">${escapeHtml(e.message||'Unable to load admin accounts.')}</div>`}}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function resetForm(){form.reset();document.querySelector('#barangay-id').value='';save.textContent='Add Barangay';cancel.hidden=true}
form.addEventListener('submit',async e=>{e.preventDefault();const id=document.querySelector('#barangay-id').value;const body=Object.fromEntries(fields.map(f=>[f,document.querySelector('#'+f).value.trim()]));if(!/^[a-z0-9-]+$/.test(body.slug)){show('Slug must use lowercase letters, numbers, and hyphens.',true);return}try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/barangays${id?`?id=eq.${encodeURIComponent(id)}`:''}`,{method:id?'PATCH':'POST',headers:headers({'Prefer':'return=minimal'}),body:JSON.stringify(body)});if(!r.ok)throw new Error('Save failed. Check the slug or your permissions.');show(id?'Barangay updated.':'Barangay added.');resetForm();await loadBarangays()}catch(e){show(e.message||'Save failed.',true)}})
adminForm.addEventListener('submit',async e=>{e.preventDefault();const full_name=document.querySelector('#admin-full-name').value.trim(),email=document.querySelector('#admin-email').value.trim(),password=document.querySelector('#admin-password').value,barangay_id=adminBarangay.value;if(!full_name||!email||!password||!barangay_id){showAdmin('Complete the name, email, password, and assigned barangay.',true);return}adminSave.disabled=true;showAdmin('Creating admin account…');try{const r=await fetch(`${SUPABASE_CONFIG.url}/functions/v1/create-barangay-admin`,{method:'POST',headers:headers(),body:JSON.stringify({full_name,email,password,barangay_id})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||'Unable to create the admin account.');showAdmin(data.message||'Admin account created and pending approval.');adminForm.reset();await loadAdmins()}catch(e){showAdmin(e.message||'Unable to create the admin account.',true)}finally{adminSave.disabled=false}})
adminQueue.addEventListener('click',async e=>{const approve=e.target.closest('[data-approve]'),reject=e.target.closest('[data-reject]');const id=approve?.dataset.approve||reject?.dataset.reject;if(!id)return;const next=approve?'approved':'rejected';if(!confirm(`${approve?'Approve':'Reject'} this Barangay Admin account?`))return;try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:headers({'Prefer':'return=minimal'}),body:JSON.stringify({approval_status:next})});if(!r.ok)throw new Error('Approval update failed.');showAdmin(`Admin account ${next}.`);await loadAdmins()}catch(e){showAdmin(e.message||'Approval update failed.',true)}})
list.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),toggle=e.target.closest('[data-toggle]');if(edit){const b=barangays.find(x=>x.id===edit.dataset.edit);if(!b)return;fields.forEach(f=>document.querySelector('#'+f).value=b[f]||'');document.querySelector('#barangay-id').value=b.id;save.textContent='Save Changes';cancel.hidden=false;document.querySelector('#barangays-section').scrollIntoView({behavior:'smooth'})}if(toggle){const b=barangays.find(x=>x.id===toggle.dataset.toggle);if(!b)return;try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/barangays?id=eq.${encodeURIComponent(b.id)}`,{method:'PATCH',headers:headers({'Prefer':'return=minimal'}),body:JSON.stringify({status:b.status==='active'?'inactive':'active'})});if(!r.ok)throw new Error('Status update failed.');show(`Barangay ${b.status==='active'?'deactivated':'activated'}.`);await loadBarangays()}catch(e){show(e.message||'Status update failed.',true)}}})
search.addEventListener('input',render);cancel.addEventListener('click',resetForm);document.querySelector('#refresh-admins')?.addEventListener('click',loadAdmins);document.querySelector('#logout').addEventListener('click',()=>{sessionStorage.removeItem('brgywebsaas_session');window.location.replace('login.html')});
document.querySelectorAll('[data-section]').forEach(btn=>btn.addEventListener('click',()=>{const target=btn.dataset.section;document.querySelectorAll('.app-section').forEach(s=>s.hidden=true);const section=document.querySelector(`#${target}-section`);if(section){section.hidden=false;section.scrollIntoView({behavior:'smooth')}document.querySelectorAll('.nav-link-btn').forEach(n=>n.classList.toggle('active',n.dataset.section===target));if(target==='admins')loadAdmins()}));
function openCustomizer(){document.querySelector('#theme-open')?.click()}
document.querySelector('#open-theme-settings')?.addEventListener('click',openCustomizer);document.querySelector('#theme-open-inline')?.addEventListener('click',openCustomizer);document.querySelector('#quick-add')?.addEventListener('click',()=>{resetForm();document.querySelector('#barangays-section')?.removeAttribute('hidden');document.querySelector('#barangays-section')?.scrollIntoView({behavior:'smooth'});document.querySelector('#name')?.focus()});
