import {SUPABASE_CONFIG} from './config.js';
const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');
if(!session?.access_token||String(session.profile?.role||'').toLowerCase()!=='super_admin'||session.profile.approval_status!=='approved'){location.replace('superadmin-login.html');throw Error('Unauthorized')}
const $=s=>document.querySelector(s),status=$('#status');
const MAX=1024*1024;
const bases=[['Civic Executive','#0f6ea8','#0f766e','#0284c7','#f1f5f9','#0f172a','#fff','Inter','Government / Formal'],['Government Blue','#1e3a8a','#334155','#3b82f6','#f8fafc','#0f172a','#fff','Inter','Government / Formal'],['Modern Authority','#111827','#374151','#6366f1','#f8fafc','#111827','#111827','Inter','Executive / Corporate'],['Municipal Classic','#7f1d1d','#991b1b','#b45309','#fffaf5','#29160f','#fff','Georgia','Government / Formal'],['Clean Administration','#334155','#475569','#64748b','#f8fafc','#0f172a','#fff','Arial','Modern / Minimal'],['Fluent Civic','#2563eb','#0f766e','#06b6d4','#f8fafc','#0f172a','#fff','Inter','Civic / Community'],['Material Civic','#4f46e5','#6d28d9','#818cf8','#f5f3ff','#17152d','#fff','Inter','Modern / Minimal'],['Carbon Authority','#161616','#525252','#0f62fe','#f4f4f4','#161616','#161616','Arial','Executive / Corporate'],['Emerald Public Service','#047857','#065f46','#10b981','#f0fdf4','#10231b','#fff','Trebuchet MS','Civic / Community'],['Indigo Government','#4338ca','#5b21b6','#6366f1','#eef2ff','#17152d','#fff','Inter','Government / Formal']];
const navs=['Top Navigation','Compact Top Bar','Centered Navigation','Left Sidebar','Dark Sidebar'];const footers=['Standard Footer','Minimal Footer','Compact Footer','Institutional Footer'];const radii=['small','medium','large'];const fonts=['Inter,ui-sans-serif,system-ui,sans-serif','Arial,sans-serif','Georgia,serif','Trebuchet MS,sans-serif','Verdana,sans-serif'];
const PRESETS=Array.from({length:100},(_,i)=>{const b=bases[i%bases.length],n=navs[Math.floor(i/navs.length)%navs.length],f=footers[Math.floor(i/4)%footers.length],font=fonts[Math.floor(i/7)%fonts.length];return {id:i+1,label:b[0]+(i>=10?' '+String(i+1).padStart(2,'0'):''),category:b[8],primary:b[1],secondary:b[2],accent:b[3],background:b[4],text:b[5],navbar:b[6],font,mode:(i%11===4||i%11===9)?'dark':'light',radius:radii[i%3],nav:n,footer:f,layout:i%5===3?'sidebar':'dashboard',recommended:i<10}});
let selected=1,currentSettings={};
function show(m,error=false){status.hidden=false;status.textContent=m;status.className=`alert mt-3 ${error?'alert-danger':'alert-success'}`}
function authHeaders(prefer='return=representation'){return {apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:prefer}}
async function readSettings(){const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings?scope=eq.super_admin&select=id,settings,is_published&limit=1`,{headers:authHeaders('return=representation')});if(!r.ok)throw Error(`Unable to load saved design (${r.status}).`);const rows=await r.json();currentSettings=rows?.[0]||{};const saved=currentSettings.settings||{};const match=PRESETS.find(p=>p.id===Number(saved.id));if(match)selected=match.id;return saved}
function render(){const q=($('#search').value||'').toLowerCase(),cat=$('#category').value;const box=$('#presets');box.innerHTML=PRESETS.filter(p=>(!cat||p.category===cat)&&`${p.label} ${p.nav} ${p.footer} ${p.font} ${p.category}`.toLowerCase().includes(q)).map(p=>`<button type="button" class="design-card ${p.id===selected?'selected':''}" data-id="${p.id}" aria-label="Select ${p.label}">${p.recommended?'<span class="design-badge">RECOMMENDED</span>':''}<div class="swatches"><i style="background:${p.primary}"></i><i style="background:${p.secondary}"></i><i style="background:${p.accent}"></i><i style="background:${p.background}"></i></div><div class="design-info"><div class="design-number">DESIGN ${String(p.id).padStart(2,'0')} · ${p.category}</div><div class="design-name">${p.label}</div><div class="design-meta">${p.font.split(',')[0]} · ${p.nav} · ${p.footer}</div></div></button>`).join('');box.querySelectorAll('[data-id]').forEach(x=>x.onclick=async()=>{selected=Number(x.dataset.id);render();await publish(true)})}
async function publish(auto=false){const p=PRESETS.find(x=>x.id===selected);if(!p)return;try{const merged={...p};if(currentSettings.settings?.logo_url)merged.logo_url=currentSettings.settings.logo_url;const id=currentSettings.id;let r;if(id){r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:authHeaders('return=representation'),body:JSON.stringify({settings:merged,is_published:true,updated_by:session.profile.id,updated_at:new Date().toISOString()})})}else{r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings`,{method:'POST',headers:authHeaders('return=representation'),body:JSON.stringify({scope:'super_admin',settings:merged,is_published:true,updated_by:session.profile.id})})}const rows=await r.json().catch(()=>[]);if(!r.ok||!rows?.length)throw Error('Design was not saved. Check Super Admin permissions.');currentSettings={...(Array.isArray(rows)?rows[0]:rows),settings:merged};localStorage.setItem('brgywebsaas_superadmin_theme',JSON.stringify(merged));show(auto?`${p.label} selected and saved automatically.`:`${p.label} published successfully.`)}catch(e){show('Unable to save design: '+(e.message||e),true)}}
function previewLogo(src){const box=$('#logo-preview');box.innerHTML=src?`<img src="${src}" alt="Super Admin logo">`:'<span class="logo-placeholder">No logo<br>uploaded</span>'}
async function compress(file){if(!file.type.match(/^image\/(png|jpeg|webp)$/))throw Error('Logo must be PNG, JPG, or WebP.');if(file.size>10*1024*1024)throw Error('Original image is too large. Maximum source size is 10 MB.');const bmp=await createImageBitmap(file);const max=512,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bmp.width*scale));canvas.height=Math.max(1,Math.round(bmp.height*scale));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);let quality=.85,blob=await new Promise(r=>canvas.toBlob(r,'image/webp',quality));while(blob&&blob.size>MAX&&quality>.45){quality-=.1;blob=await new Promise(r=>canvas.toBlob(r,'image/webp',quality))}if(!blob||blob.size>MAX)throw Error('Logo could not be compressed below 1 MB.');return blob}
async function loadLogo(){try{const saved=await readSettings();const logo=saved.logo_url||localStorage.getItem('brgywebsaas_superadmin_logo');if(logo)previewLogo(logo);render()}catch(e){const logo=localStorage.getItem('brgywebsaas_superadmin_logo');if(logo)previewLogo(logo);render();show(e.message,true)}}
async function saveSettings(settings){const id=currentSettings.id;if(!id)throw Error('Design settings record is missing.');const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:authHeaders('return=representation'),body:JSON.stringify({settings,updated_by:session.profile.id,updated_at:new Date().toISOString()})});const rows=await r.json().catch(()=>[]);if(!r.ok||!rows?.length)throw Error('Settings could not be saved.');currentSettings={...(Array.isArray(rows)?rows[0]:rows),settings}}
async function uploadLogo(file){try{const blob=await compress(file);const path='super-admin/logo.webp';const r=await fetch(`${SUPABASE_CONFIG.url}/storage/v1/object/superadmin-assets/${path}`,{method:'POST',headers:{apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'image/webp','x-upsert':'true'},body:blob});if(!r.ok)throw Error('Logo upload failed.');const publicUrl=`${SUPABASE_CONFIG.url}/storage/v1/object/public/superadmin-assets/${path}?v=${Date.now()}`;const saved={...(currentSettings.settings||PRESETS.find(p=>p.id===selected)),logo_url:publicUrl};await saveSettings(saved);localStorage.setItem('brgywebsaas_superadmin_logo',publicUrl);previewLogo(publicUrl);show(`Logo uploaded and saved (${Math.round(blob.size/1024)} KB).`)}catch(e){show('Unable to upload logo: '+(e.message||e),true)}}
async function removeLogo(){try{const r=await fetch(`${SUPABASE_CONFIG.url}/storage/v1/object/superadmin-assets/super-admin/logo.webp`,{method:'DELETE',headers:{apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`}});if(!r.ok&&r.status!==404)throw Error('Logo file could not be removed.');const saved={...(currentSettings.settings||PRESETS.find(p=>p.id===selected)),logo_url:null};await saveSettings(saved);localStorage.removeItem('brgywebsaas_superadmin_logo');previewLogo(null);show('Super Admin logo removed.')}catch(e){show('Unable to remove logo: '+(e.message||e),true)}}
const cats=[...new Set(PRESETS.map(p=>p.category))];$('#category').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);$('#publish').onclick=()=>publish(false);$('#logo-file').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)uploadLogo(f);e.target.value='' });$('#remove-logo').onclick=removeLogo;render();loadLogo();