import {SUPABASE_CONFIG} from './config.js';
const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');
if(!session?.access_token||String(session.profile?.role||'').toLowerCase()!=='super_admin'||session.profile.approval_status!=='approved'){location.replace('superadmin-login.html');throw Error('Unauthorized')}
const $=s=>document.querySelector(s),status=$('#status');
const bases=[['Civic Executive','#0f6ea8','#0f766e','#0284c7','#f1f5f9','#0f172a','#fff','Inter'],['Government Blue','#1e3a8a','#334155','#3b82f6','#f8fafc','#0f172a','#fff','Inter'],['Modern Authority','#111827','#374151','#6366f1','#f8fafc','#111827','#111827','Inter'],['Municipal Classic','#7f1d1d','#991b1b','#b45309','#fffaf5','#29160f','#fff','Georgia'],['Clean Administration','#334155','#475569','#64748b','#f8fafc','#0f172a','#fff','Arial'],['Fluent Civic','#2563eb','#0f766e','#06b6d4','#f8fafc','#0f172a','#fff','Inter'],['Material Civic','#4f46e5','#6d28d9','#818cf8','#f5f3ff','#17152d','#fff','Inter'],['Carbon Authority','#161616','#525252','#0f62fe','#f4f4f4','#161616','#161616','Arial'],['Emerald Public Service','#047857','#065f46','#10b981','#f0fdf4','#10231b','#fff','Trebuchet MS'],['Indigo Government','#4338ca','#5b21b6','#6366f1','#eef2ff','#17152d','#fff','Inter']];
const navs=['Top Navigation','Compact Top Bar','Centered Navigation','Left Sidebar','Dark Sidebar'];const footers=['Standard Footer','Minimal Footer','Compact Footer','Institutional Footer'];const radii=['small','medium','large'];const fonts=['Inter,ui-sans-serif,system-ui,sans-serif','Arial,sans-serif','Georgia,serif','Trebuchet MS,sans-serif','Verdana,sans-serif'];
const PRESETS=Array.from({length:100},(_,i)=>{const b=bases[i%bases.length],n=navs[Math.floor(i/navs.length)%navs.length],f=footers[Math.floor(i/4)%footers.length],font=fonts[Math.floor(i/7)%fonts.length];return {id:i+1,label:b[0]+(i>=10?' '+String(i+1).padStart(2,'0'):''),primary:b[1],secondary:b[2],accent:b[3],background:b[4],text:b[5],navbar:b[6],font,mode:(i%11===4||i%11===9)?'dark':'light',radius:radii[i%3],nav:n,footer:f,layout:i%5===3?'sidebar':'dashboard',recommended:i<10}});
let selected=1;
function show(m,error=false){status.hidden=false;status.textContent=m;status.className=`alert mt-3 ${error?'alert-danger':'alert-success'}`}
function render(){const q=($('#search').value||'').toLowerCase();const box=$('#presets');box.innerHTML=PRESETS.filter(p=>`${p.label} ${p.nav} ${p.footer}`.toLowerCase().includes(q)).map(p=>`<button type="button" class="design-card ${p.id===selected?'selected':''}" data-id="${p.id}" aria-label="Select ${p.label}">${p.recommended?'<span class="design-badge">RECOMMENDED</span>':''}<div class="swatches"><i style="background:${p.primary}"></i><i style="background:${p.secondary}"></i><i style="background:${p.accent}"></i><i style="background:${p.background}"></i></div><div class="design-info"><div class="design-number">DESIGN ${String(p.id).padStart(2,'0')}</div><div class="design-name">${p.label}</div><div class="design-meta">${p.font.split(',')[0]} · ${p.nav} · ${p.footer}</div></div></button>`).join('');box.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{selected=Number(x.dataset.id);render()})}
function headers(){return {apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}}
async function publish(){const p=PRESETS.find(x=>x.id===selected);try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings?scope=eq.super_admin`,{method:'PATCH',headers:headers(),body:JSON.stringify({settings:p,is_published:true,updated_by:session.profile.id,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());localStorage.setItem('brgywebsaas_superadmin_theme',JSON.stringify(p));show(`${p.label} published successfully.`)}catch(e){show('Unable to publish design: '+e.message,true)}}
$('#search').addEventListener('input',render);$('#publish').onclick=publish;render();