import {SUPABASE_CONFIG} from './config.js';
const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');
const role=String(session?.profile?.role||'').toLowerCase();
if(!session?.access_token||role!=='super_admin'||session.profile.approval_status!=='approved'){location.replace('superadmin-login.html');throw Error('Unauthorized')}
const $=s=>document.querySelector(s);const status=$('#status');
const PRESETS={
 ocean:{label:'Ocean Professional',primary:'#0f6ea8',secondary:'#0f766e',accent:'#0284c7',background:'#f1f5f9',text:'#0f172a',navbar:'#ffffff',font:'Inter,ui-sans-serif,system-ui,sans-serif',mode:'light',radius:'medium'},
 navy:{label:'Executive Navy',primary:'#1e3a8a',secondary:'#334155',accent:'#3b82f6',background:'#f8fafc',text:'#0f172a',navbar:'#ffffff',font:'Inter,ui-sans-serif,system-ui,sans-serif',mode:'light',radius:'medium'},
 slate:{label:'Modern Slate',primary:'#334155',secondary:'#475569',accent:'#64748b',background:'#f8fafc',text:'#0f172a',navbar:'#0f172a',font:'Inter,ui-sans-serif,system-ui,sans-serif',mode:'dark',radius:'medium'},
 emerald:{label:'Civic Emerald',primary:'#047857',secondary:'#065f46',accent:'#10b981',background:'#f0fdf4',text:'#10231b',navbar:'#ffffff',font:'Trebuchet MS,sans-serif',mode:'light',radius:'large'},
 indigo:{label:'Indigo Modern',primary:'#4f46e5',secondary:'#6d28d9',accent:'#818cf8',background:'#f5f3ff',text:'#17152d',navbar:'#ffffff',font:'Inter,ui-sans-serif,system-ui,sans-serif',mode:'light',radius:'large'},
 graphite:{label:'Graphite Executive',primary:'#111827',secondary:'#374151',accent:'#6b7280',background:'#f3f4f6',text:'#111827',navbar:'#111827',font:'Arial,sans-serif',mode:'dark',radius:'small'},
 burgundy:{label:'Burgundy Formal',primary:'#7f1d1d',secondary:'#991b1b',accent:'#b45309',background:'#fffaf5',text:'#29160f',navbar:'#ffffff',font:'Georgia,serif',mode:'light',radius:'medium'},
 teal:{label:'Teal Civic',primary:'#0f766e',secondary:'#115e59',accent:'#14b8a6',background:'#f0fdfa',text:'#10231f',navbar:'#ffffff',font:'Inter,ui-sans-serif,system-ui,sans-serif',mode:'light',radius:'medium'}
};
function show(m,error=false){status.hidden=false;status.textContent=m;status.className=`alert mt-3 ${error?'alert-danger':'alert-success'}`}
function headers(extra={}){return {apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...extra}}
function values(){return Object.fromEntries(['font','primary','secondary','accent','background','text','navbar','mode','radius'].map(id=>[id,$('#'+id).value]))}
function apply(v){Object.entries({'--brand-primary':v.primary,'--brand-secondary':v.secondary,'--brand-accent':v.accent,'--page-bg':v.background,'--text':v.text,'--nav-bg':v.navbar,'--nav-text':v.mode==='dark'?'#f8fafc':v.text,'--surface':v.mode==='dark'?'#111827':'#ffffff','--muted':v.mode==='dark'?'#94a3b8':'#64748b','--border':v.mode==='dark'?'#334155':'#dbe4ee'}).forEach(([k,x])=>document.documentElement.style.setProperty(k,x));document.documentElement.dataset.themeMode=v.mode;document.documentElement.dataset.radius=v.radius;document.body.style.fontFamily=v.font;const p=$('#preview');p.style.setProperty('--studio-primary',v.primary);p.style.setProperty('--studio-secondary',v.secondary);p.style.setProperty('--studio-accent',v.accent);p.style.setProperty('--studio-bg',v.background);p.style.setProperty('--studio-text',v.text);p.style.setProperty('--studio-nav',v.navbar);p.style.setProperty('--studio-font',v.font);}
function fill(v){for(const [k,x] of Object.entries(v))if($('#'+k))$('#'+k).value=x;apply(values())}
function renderPresets(){const box=$('#presets');box.innerHTML=Object.entries(PRESETS).map(([key,p])=>`<button type="button" class="btn btn-outline-secondary text-start" data-preset="${key}"><strong>${p.label}</strong><span class="small d-block text-body-secondary">${p.primary} · ${p.accent}</span></button>`).join('');box.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>fill(PRESETS[b.dataset.preset]))}
async function load(){try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings?scope=eq.super_admin&select=*&limit=1`,{headers:headers()});if(!r.ok)throw Error('Unable to load Super Admin design.');const rows=await r.json();const s=rows[0]?.settings;if(s)fill({...PRESETS.ocean,...s});else fill(PRESETS.ocean)}catch(e){fill(PRESETS.ocean);show(e.message,true)}}
async function save(publish){const settings=values();try{const r=await fetch(`${SUPABASE_CONFIG.url}/rest/v1/system_design_settings`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({scope:'super_admin',settings,is_published:publish})});if(!r.ok)throw Error('Unable to save Super Admin design.');localStorage.setItem('brgywebsaas_superadmin_theme',JSON.stringify(settings));show(publish?'Super Admin design published.':'Super Admin design saved.')}catch(e){show(e.message,true)}}
['font','primary','secondary','accent','background','text','navbar','mode','radius'].forEach(id=>$('#'+id).addEventListener('input',()=>apply(values())));$('#save').onclick=()=>save(false);$('#publish').onclick=()=>save(true);renderPresets();load();