import {SUPABASE_CONFIG} from './config.js';
const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const headers=(extra={})=>({apikey:SUPABASE_CONFIG.publishableKey,Authorization:`Bearer ${session?.access_token}`,'Content-Type':'application/json',...extra});
let barangays=[],admins=[],selected=null;
function ok(){return session?.access_token&&session?.profile&&String(session.profile.role).toLowerCase()==='super_admin'&&session.profile.approval_status==='approved'}
if(!ok()){sessionStorage.removeItem('brgywebsaas_session');location.replace('superadmin-login.html');throw Error('unauthorized')}
$('#welcome').textContent=`Signed in as ${session.profile.full_name||session.user?.email||'Super Admin'}`;
function msg(el,text,error=false){if(!el)return;el.textContent=text;el.dataset.state=error?'error':'ok';el.hidden=false}
async function api(path,options={}){const {headers:extraHeaders,...rest}=options;const r=await fetch(`${SUPABASE_CONFIG.url}${path}`,{...rest,headers:headers(extraHeaders||{})});if(!r.ok){let d={};try{d=await r.json()}catch{}throw Error(d.message||d.error||`Request failed (${r.status})`)}return r.status===204?null:r.json().catch(()=>null)}
function slugify(value){return String(value||'').trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').replace(/-{2,}/g,'-')}
function normalizeSlugField(){const el=$('#slug');if(!el)return;el.value=slugify(el.value)}
function normalizeDomain(value){return String(value||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/.*$/,'').replace(/\.$/,'')}
function validDomain(value){return !value||/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(value)}
$('#slug')?.addEventListener('input',normalizeSlugField);
$('#custom-domain')?.addEventListener('blur',e=>{e.target.value=normalizeDomain(e.target.value)});
$('#name')?.addEventListener('blur',()=>{const slug=$('#slug');if(slug&&!slug.value.trim())slug.value=slugify($('#name').value)});
async function loadBarangays(){try{barangays=await api('/rest/v1/barangays?select=id,name,slug,municipality,province,status,custom_domain,created_at&order=name.asc');renderBarangays();renderStats();populateManager()}catch(e){msg($('#status'),e.message,true)}}
function renderStats(){$('#total-count').textContent=barangays.length;$('#active-count').textContent=barangays.filter(x=>x.status==='active').length;$('#inactive-count').textContent=barangays.filter(x=>x.status!=='active').length}
function adminLoginUrl(b){return `login.html?barangay=${encodeURIComponent(b.slug)}`}
function publicUrl(b){return `barangay.html?id=${encodeURIComponent(b.id)}`}
function renderDashboard(){$('#dashboard-list').innerHTML=barangays.slice(0,6).map(b=>`<div class="list-group-item px-0 py-3" style="background:transparent;border-color:var(--border)"><div class="d-flex justify-content-between gap-2 flex-wrap"><div><strong>${esc(b.name)}</strong><div class="muted small">${esc(b.municipality||'')} ${esc(b.province||'')}</div></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-sm btn-outline-primary" href="${adminLoginUrl(b)}">${esc(b.name)} Admin Login</a><a class="btn btn-sm btn-outline-secondary" href="${publicUrl(b)}" target="_blank" rel="noopener">Public View</a></div></div></div>`).join('')||'<p class="muted mb-0">No barangays yet.</p>'}
function renderBarangays(){const q=($('#search')?.value||'').trim().toLowerCase();const rows=barangays.filter(b=>[b.name,b.slug,b.municipality,b.province,b.custom_domain].some(v=>String(v||'').toLowerCase().includes(q)));$('#barangays').innerHTML=rows.length?rows.map(b=>`<article><div class="flex-grow-1 min-w-0"><strong>${esc(b.name)}</strong><div class="muted">${esc(b.municipality||'')} ${esc(b.province||'')} · ${esc(b.status)}</div><div class="domain-box"><span class="domain-label">Site:</span> <span class="domain-value">${b.custom_domain?esc(b.custom_domain):`/${esc(b.slug)}`}</span></div></div><div class="barangay-actions"><a class="btn btn-sm btn-primary" href="${adminLoginUrl(b)}">${esc(b.name)} Admin Login</a><a class="btn btn-sm btn-outline-primary" href="${publicUrl(b)}" target="_blank" rel="noopener">Public View</a><button class="btn btn-sm btn-outline-secondary" data-domain="${b.id}" type="button">Customize Domain</button><button class="btn btn-sm btn-outline-primary" data-edit="${b.id}" type="button">Edit</button><button class="btn btn-sm btn-outline-secondary" data-toggle="${b.id}" type="button">${b.status==='active'?'Deactivate':'Activate'}</button><button class="btn btn-sm btn-outline-danger" data-delete="${b.id}" type="button">Delete</button></div></article>`).join(''):'<div class="muted py-3">No barangays found.</div>';renderDashboard();const limit=barangays.length>=20;$('#save').disabled=limit&&!$('#barangay-id').value;$('#save').title=limit&&!$('#barangay-id').value?'Maximum of 20 barangays reached.':' '}
function populateManager(){const s=$('#admin-manager-barangay');if(!s)return;const current=s.value;s.innerHTML='<option value="">Select a barangay…</option>'+barangays.filter(b=>b.status==='active').map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('');if(current)s.value=current}
async function loadAdmins(){try{admins=await api('/rest/v1/profiles?role=eq.barangay_admin&select=id,full_name,email,role,barangay_id,approval_status,created_at&order=created_at.asc');renderSlots()}catch(e){msg($('#admin-status'),e.message,true)}}
function renderSlots(){const box=$('#slot-list');if(!box)return;if(!selected){box.innerHTML='';return}const own=admins.filter(a=>a.barangay_id===selected.id).slice(0,2);$('#selected-barangay').innerHTML=`<strong>${esc(selected.name)}</strong> · ${own.length}/2 admin accounts`;box.innerHTML=own.map((a,i)=>slot(a,i+1)).join('');$('#add-admin-slot').disabled=own.length>=2;$('#add-admin-slot').title=own.length>=2?'Maximum of 2 admin accounts for this barangay.':' '}
function slot(a,n){const state=a.approval_status||'pending';return `<article class="admin-slot"><div class="admin-slot-head"><div><div class="barangay-tag">${esc(selected.name)}</div><strong>Slot ${String(n).padStart(2,'0')} / 02</strong></div><button class="admin-slot-logo" title="Super Admin context" data-super="${a.id}" type="button">B</button></div><div class="mt-2"><strong>${esc(a.full_name||'Unnamed admin')}</strong><div class="muted small">${esc(a.email||'Login account')}</div></div><div class="small mt-2">Status: <strong>${esc(state)}</strong></div><div class="slot-actions"><button class="btn btn-sm btn-outline-primary" data-edit-admin="${a.id}" type="button">Edit</button>${state==='pending'?`<button class="btn btn-sm btn-success" data-approve="${a.id}" type="button">Approve</button><button class="btn btn-sm btn-outline-danger" data-reject="${a.id}" type="button">Reject</button>`:''}<button class="btn btn-sm btn-outline-primary" data-admin-login="${selected.id}" type="button">Admin Login</button><a class="btn btn-sm btn-outline-secondary" href="${publicUrl(selected)}" target="_blank" rel="noopener">Public View</a></div></article>`}
function openEditor(a=null){if(!selected)return;$('#admin-edit-panel').hidden=false;$('#admin-profile-id').value=a?.id||'';$('#admin-slot-number').value=a?admins.filter(x=>x.barangay_id===selected.id).findIndex(x=>x.id===a.id)+1:admins.filter(x=>x.barangay_id===selected.id).length+1;$('#admin-full-name').value=a?.full_name||'';$('#admin-email').value=a?.email||'';$('#admin-password').value='';$('#admin-assigned-readonly').value=selected.name;$('#admin-edit-title').textContent=a?`Edit Admin · Slot ${String($('#admin-slot-number').value).padStart(2,'0')}`:`New Admin · Slot ${String($('#admin-slot-number').value).padStart(2,'0')}`;$('#admin-edit-context').textContent=`Assigned Barangay: ${selected.name}`}
function editBarangay(b,focusDomain=false){$('#name').value=b.name||'';$('#slug').value=slugify(b.slug||b.name);$('#municipality').value=b.municipality||'';$('#province').value=b.province||'';$('#custom-domain').value=b.custom_domain||'';$('#barangay-id').value=b.id;$('#save').textContent='Save Changes';$('#cancel').hidden=false;if(focusDomain){document.querySelector('[data-section="barangays"]')?.click();setTimeout(()=>$('#custom-domain')?.focus(),50)}}
$('#admin-manager-barangay')?.addEventListener('change',async e=>{selected=barangays.find(b=>b.id===e.target.value)||null;renderSlots();if(selected)await loadAdmins()});
$('#add-admin-slot')?.addEventListener('click',()=>{if(!selected){msg($('#admin-status'),'Select a barangay first.',true);return}const count=admins.filter(a=>a.barangay_id===selected.id).length;if(count>=2){msg($('#admin-status'),'This barangay already has the maximum of 2 admin accounts.',true);return}openEditor()});
$('#close-admin-edit')?.addEventListener('click',()=>$('#admin-edit-panel').hidden=true);
$('#admin-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!selected)return;const id=$('#admin-profile-id').value,body={full_name:$('#admin-full-name').value.trim(),email:$('#admin-email').value.trim()};const password=$('#admin-password').value;const count=admins.filter(a=>a.barangay_id===selected.id).length;if(!id&&count>=2){msg($('#admin-status'),'This barangay already has the maximum of 2 admin accounts.',true);return}if(!body.full_name||!body.email){msg($('#admin-status'),'Name and email are required.',true);return}if(!id&&!password){msg($('#admin-status'),'Temporary password is required for a new account.',true);return}$('#admin-save').disabled=true;try{if(id){await api(`/rest/v1/profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});msg($('#admin-status'),'Admin updated.')}else{const r=await api('/functions/v1/create-barangay-admin',{method:'POST',body:JSON.stringify({...body,password,barangay_id:selected.id})});msg($('#admin-status'),r?.message||'Admin created and pending approval.')}$('#admin-edit-panel').hidden=true;await loadAdmins()}catch(e){msg($('#admin-status'),e.message,true)}finally{$('#admin-save').disabled=false}});
$('#slot-list')?.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-admin]'),approve=e.target.closest('[data-approve]'),reject=e.target.closest('[data-reject]'),view=e.target.closest('[data-view-dashboard]'),adminLogin=e.target.closest('[data-admin-login]');if(edit){openEditor(admins.find(a=>a.id===edit.dataset.editAdmin));return}if(adminLogin){location.href=adminLoginUrl(selected);return}if(view){location.href=`admin.html?barangay_id=${encodeURIComponent(view.dataset.viewDashboard)}&super_admin_view=1`;return}const id=approve?.dataset.approve||reject?.dataset.reject;if(!id)return;const next=approve?'approved':'rejected';if(!confirm(`${approve?'Approve':'Reject'} this Barangay Admin account?`))return;try{await api(`/rest/v1/profiles?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({approval_status:next})});msg($('#admin-status'),`Admin account ${next}.`);await loadAdmins()}catch(e){msg($('#admin-status'),e.message,true)}});
$('#barangays')?.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),toggle=e.target.closest('[data-toggle]'),domain=e.target.closest('[data-domain]'),del=e.target.closest('[data-delete]');if(domain){const b=barangays.find(x=>x.id===domain.dataset.domain);if(b)editBarangay(b,true);return}if(edit){const b=barangays.find(x=>x.id===edit.dataset.edit);if(b)editBarangay(b);return}if(toggle){const b=barangays.find(x=>x.id===toggle.dataset.toggle);try{await api(`/rest/v1/barangays?id=eq.${encodeURIComponent(b.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:b.status==='active'?'inactive':'active'})});await loadBarangays()}catch(e){msg($('#status'),e.message,true)}return}if(del){const b=barangays.find(x=>x.id===del.dataset.delete);if(!b)return;if(!confirm(`Delete ${b.name}? This permanently removes the barangay record and may affect its assigned admin accounts. This cannot be undone.`))return;del.disabled=true;try{await api(`/rest/v1/barangays?id=eq.${encodeURIComponent(b.id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});msg($('#status'),`Barangay ${b.name} deleted.`);await loadBarangays();await loadAdmins()}catch(e){msg($('#status'),`Could not delete ${b.name}: ${e.message}. If it has assigned admin accounts, remove/reassign those accounts first.`,true)}finally{del.disabled=false}}});
$('#search')?.addEventListener('input',renderBarangays);$('#cancel')?.addEventListener('click',()=>{$('#barangay-form')?.reset();$('#barangay-id').value='';$('#save').textContent='Add Barangay';$('#cancel').hidden=true;renderBarangays()});
$('#refresh-admins')?.addEventListener('click',loadAdmins);
$('#logout')?.addEventListener('click',()=>{sessionStorage.removeItem('brgywebsaas_session');location.replace('superadmin-login.html')});
document.querySelectorAll('[data-section]').forEach(btn=>btn.addEventListener('click',()=>{const t=btn.dataset.section;document.querySelectorAll('.app-section').forEach(s=>s.hidden=true);const sec=$(`#${t}-section`);if(sec)sec.hidden=false;document.querySelectorAll('.nav-link-btn').forEach(n=>n.classList.toggle('active',n.dataset.section===t));if(t==='admins')loadAdmins()}));
$('#barangay-form')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#barangay-id').value;if(!id&&barangays.length>=20){msg($('#status'),'Maximum of 20 barangays reached.',true);return}normalizeSlugField();const body={name:$('#name').value.trim(),slug:$('#slug').value.trim(),municipality:$('#municipality').value.trim(),province:$('#province').value.trim(),custom_domain:normalizeDomain($('#custom-domain').value)};if(!body.name){msg($('#status'),'Barangay name is required.',true);return}if(!body.slug){msg($('#status'),'Site URL slug is required.',true);return}if(!/^[a-z0-9-]+$/.test(body.slug)){msg($('#status'),'Slug must use lowercase letters, numbers, and hyphens.',true);return}if(!validDomain(body.custom_domain)){msg($('#status'),'Enter a valid domain such as www.example.gov.ph.',true);return}try{await api(`/rest/v1/barangays${id?`?id=eq.${encodeURIComponent(id)}`:''}`,{method:id?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});msg($('#status'),id?'Barangay updated.':'Barangay added.');e.target.reset();$('#barangay-id').value='';$('#save').textContent='Add Barangay';$('#cancel').hidden=true;await loadBarangays()}catch(e){msg($('#status'),e.message,true)}});
loadBarangays();loadAdmins();
