const THEMES={ocean:{label:'Ocean Blue',primary:'#0f6ea8',secondary:'#0f766e',accent:'#0284c7',bg:'#f1f5f9',surface:'#fff',text:'#0f172a',muted:'#64748b',border:'#dbe4ee',nav:'#fff',navText:'#0f172a'}};
const KEY='brgywebsaas_theme';
const saved=JSON.parse(localStorage.getItem(KEY)||'null');
const current={name:saved?.name||'ocean',mode:saved?.mode||'light',density:saved?.density||'comfortable',nav:saved?.nav||'top',radius:saved?.radius||'medium'};
function applyTheme(){const t=THEMES[current.name]||THEMES.ocean,r=document.documentElement;Object.entries({'--brand-primary':t.primary,'--brand-secondary':t.secondary,'--brand-accent':t.accent,'--page-bg':t.bg,'--surface':t.surface,'--text':t.text,'--muted':t.muted,'--border':t.border,'--nav-bg':t.nav,'--nav-text':t.navText}).forEach(([k,v])=>r.style.setProperty(k,v));r.dataset.themeMode=current.mode;r.dataset.density=current.density;r.dataset.navStyle=current.nav;r.dataset.radius=current.radius;localStorage.setItem(KEY,JSON.stringify(current))}
async function applySuperAdminDesign(){if(!location.pathname.endsWith('superadmin.html')&&!location.pathname.endsWith('superadmin-login.html'))return;try{const c=await import('./config.js');const session=JSON.parse(sessionStorage.getItem('brgywebsaas_session')||'null');const h={apikey:c.SUPABASE_CONFIG.publishableKey};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;const r=await fetch(`${c.SUPABASE_CONFIG.url}/rest/v1/system_design_settings?scope=eq.super_admin&select=settings,is_published&limit=1`,{headers:h});if(!r.ok)return;const row=(await r.json())[0];if(!row?.is_published||!row.settings)return;const s=row.settings;const root=document.documentElement;const map={font:s.font,'--brand-primary':s.primary,'--brand-secondary':s.secondary,'--brand-accent':s.accent,'--page-bg':s.background,'--text':s.text,'--nav-bg':s.navbar,'--nav-text':s.mode==='dark'?'#f8fafc':s.text};Object.entries(map).forEach(([k,v])=>{if(k==='font')document.body.style.fontFamily=v;else root.style.setProperty(k,v)});root.dataset.themeMode=s.mode||'light';root.dataset.radius=s.radius||'medium';localStorage.setItem('brgywebsaas_superadmin_theme',JSON.stringify(s))}catch(e){const s=JSON.parse(localStorage.getItem('brgywebsaas_superadmin_theme')||'null');if(s){const root=document.documentElement;const map={'--brand-primary':s.primary,'--brand-secondary':s.secondary,'--brand-accent':s.accent,'--page-bg':s.background,'--text':s.text,'--nav-bg':s.navbar,'--nav-text':s.mode==='dark'?'#f8fafc':s.text};Object.entries(map).forEach(([k,v])=>root.style.setProperty(k,v));if(s.font)document.body.style.fontFamily=s.font;root.dataset.themeMode=s.mode||'light';root.dataset.radius=s.radius||'medium'}}}
function cleanSuperAdminNav(){if(!document.querySelector('.super-sidebar'))return;const nav=document.querySelector('.super-sidebar .side-nav');if(!nav)return;const items=[...nav.querySelectorAll('button')];const settings=items.find(b=>b.dataset.section==='settings');items.filter(b=>!b.dataset.section).forEach(b=>b.remove());const settingsItems=items.filter(b=>b.dataset.section==='settings');settingsItems.slice(1).forEach(b=>b.remove());if(settings){settings.querySelector('span:nth-child(2)')?.replaceChildren(document.createTextNode('Settings'));settings.querySelector('span:nth-child(3)')?.replaceChildren(document.createTextNode(''))}}
function addManageAdminButtons(){const list=document.querySelector('#barangays');if(!list)return;list.querySelectorAll('article').forEach(article=>{if(article.querySelector('[data-manage-admin]'))return;const publicLink=article.querySelector('a[href*="barangay.html?id="]');if(!publicLink)return;const id=new URL(publicLink.href,location.href).searchParams.get('id');if(!id)return;const actions=article.querySelector('.barangay-actions');if(!actions)return;const btn=document.createElement('button');btn.className='btn btn-sm btn-outline-primary';btn.type='button';btn.dataset.manageAdmin=id;btn.textContent='Manage Admin';actions.insertBefore(btn,actions.firstChild);btn.addEventListener('click',()=>{const select=document.querySelector('#admin-manager-barangay');const nav=document.querySelector('[data-section="admins"]');if(select){select.value=id;select.dispatchEvent(new Event('change',{bubbles:true}))}nav?.click()})})}
function setup(){cleanSuperAdminNav();const list=document.querySelector('#barangays');if(list){const observer=new MutationObserver(addManageAdminButtons);observer.observe(list,{childList:true,subtree:true});addManageAdminButtons()}}
applyTheme();applySuperAdminDesign();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();